[http_server]
host = "0.0.0.0"
port = 3000

[database]
type = "mysql"
host = "0.0.0.0"
port = 3312
username = "root"
password = ""
dbname = "wcwd"

[token_manager]
secret = "JUSTLEARNINGSOMETHINGFORME20191226"