version: '3'

services:
  mysql:
    build: 
      context: .
      dockerfile: docker/mysql/Dockerfile
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      - MYSQL_DATABASE=wcwd
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
    ports:
      - "3377:3306"
    networks:
      - backend
  golang:
    build: 
      context: .
      dockerfile: docker/golang/Dockerfile
    volumes:
      - $PWD/apis:/app/apis
      - $PWD/core:/app/core
      - $PWD/engines:/app/engines
      - $PWD/model:/app/model
      - $PWD/config.toml:/app/config.toml
      - $PWD/main.go:/app/main.go
    ports:
      - "3000:3000"
    entrypoint: /entrypoint.sh -d mysql:3306 -c './wcwd';
    networks:
      - backend
networks:
  backend:
    driver: bridge